#!/bin/sh

# pull request ref
REF="pull/${DRONE_PULL_REQUEST}/head"

# pull request ref, bitbucket
if [[ $DRONE_REMOTE_URL = "https://bitbucket.org/"* ]]; then
	REF="refs/pull-requests/${DRONE_PULL_REQUEST}/from"
fi

# pull request ref, gitlab
if [[ $DRONE_COMMIT_REF = "refs/merge-requests/"* ]]; then
	REF="refs/merge-requests/${DRONE_PULL_REQUEST}/head"
fi

FLAGS=""
if [[ ! -z "${PLUGIN_DEPTH}" ]]; then
	FLAGS="--depth=${PLUGIN_DEPTH}"
fi

if [ ! -d .git ]; then
	git init
	git remote add origin ${DRONE_REMOTE_URL}
fi

set -e
set -x

git fetch ${FLAGS} origin +refs/heads/${DRONE_BRANCH}:
git checkout ${DRONE_BRANCH}

git fetch origin ${REF}:
git rebase ${DRONE_COMMIT}

# git clone ${FLAGS} -b ${DRONE_BRANCH} --single-branch ${DRONE_REMOTE_URL} \
#   ${DRONE_WORKSPACE}
#
# git fetch origin pull/${DRONE_PULL_REQUEST}/head:
# git rebase ${DRONE_COMMIT}
