#!/bin/sh

FLAGS=""
if [[ ! -z "${PLUGIN_DEPTH}" ]]; then
	FLAGS="--depth=${PLUGIN_DEPTH}"
fi

if [ ! -d .git ]; then
	git init
	git remote add origin ${DRONE_REMOTE_URL}
fi

set -e
set -x

git fetch ${FLAGS} origin +refs/tags/${DRONE_TAG}:
git checkout -qf FETCH_HEAD

#
# this code is optimized for cloning a single
# branch if the target directory is empty and
# will use the tag as the branch name.
#
#
# git clone --branch ${DRONE_TAG} --single-branch \
#   ${DRONE_REMOTE_URL} ${DRONE_WORKSPACE}
#
