#!/bin/sh

# pull request ref
REF="pull/${DRONE_PULL_REQUEST}/head"

# pull request ref, bitbucket
# case being used because pattern matching in /bin/sh needs to use case.
case "$DRONE_REMOTE_URL" in
    "https://bitbucket.org/"*) REF="refs/pull-requests/${DRONE_PULL_REQUEST}/from" ;;
    *) ;;
esac

# pull request ref, gitlab
# case being used because pattern matching in /bin/sh needs to use case.
case "$DRONE_COMMIT_REF" in
    "refs/merge-requests/"*) REF="refs/merge-requests/${DRONE_PULL_REQUEST}/head" ;;
    *) ;;
esac

FLAGS=""
if [[ ! -z "${PLUGIN_DEPTH}" ]]; then
	FLAGS="--depth=${PLUGIN_DEPTH}"
fi

if [ ! -d .git ]; then
	git init
	git remote add origin ${DRONE_REMOTE_URL}
fi

set -e
set -x

git fetch ${FLAGS} origin +refs/heads/${DRONE_BRANCH}:
git checkout ${DRONE_BRANCH}

git fetch origin ${REF}:
git merge ${DRONE_COMMIT}

# git clone ${FLAGS} -b ${DRONE_BRANCH} --single-branch ${DRONE_REMOTE_URL} \
#   ${DRONE_WORKSPACE}
#
# git fetch origin pull/${DRONE_PULL_REQUEST}/head:
# git rebase ${DRONE_COMMIT}
