# CGO_ENABLED=0 GOOS=linux GOARCH=arm go build -a -tags netgo
# docker build --rm=true -f Dockerfile.armhf -t plugins/git:arm .

FROM scaleway/alpine:armhf-latest

RUN apk update && \
  apk add \
    ca-certificates \
    git \
    openssh \
    curl \
    perl && \
  rm -rf /var/cache/apk/*

ADD drone-git /bin/
ENTRYPOINT ["/bin/drone-git"]
